### ISSUE TITLE
[DEFECT] OMM 5.0 requires at least one usernamespace to have userNamespace:true

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#69] opened 2023-07-07 00:26 UTC
https://jira.jpl.nasa.gov/browse/OMM-173

**Describe the defect**

**Expected behavior**

**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Environment (please complete the following information):**
 - Version []
 - Browser []

**Additional context**
Add any other context, code snippets, error messages, screen shots about the problem here.

|Criticality|Name|Description|
|---|---|---|
|crit1|Critical|Defect makes the software unusable for mission operations.|
|crit2|Major|Defect has significant impact on usability of delivered software for mission operations. User experience is difficult and/or cumbersome. Workaround available is arduous.|
|crit3|Moderate|Defect has moderate to mild impact on usability of delivered software for mission operations. User experience is degraded but workable.|
|crit4|Minor|Defect means software does not work as originally intended, but the defect has little impact on the usability of the delivered software.|

**Comment by jvigliotta** [comment] 2023-07-18 17:01
dupe of #55

**Closed by jvigliotta** 2023-07-18 17:01 UTC
Labels: defect, crit-3
