### ISSUE TITLE
[DEFECT] Tables disappearing inside tab views

### ISSUE THREAD

**Issue by chesterhawkins** [NASA-AMMOS/openmct-mcws#40] opened 2023-05-30 17:34 UTC
Describe the defect
In a Tab view with multiple channel table sets the tables disappeared for multiple users.
Users were able to click to other tabs within the tab view and the tables within those views had also disappeared.

Version - v5.0.0-b3
Browser - Chrome

**Comment by davetsay** [comment] 2023-06-13 20:19
Caused by changes in R5.0 and fixed during formal testing.

**Comment by davetsay** [comment] 2023-06-13 23:01
@chesterhawkins , actually before I close this, can you verify if this is still happening?

**Comment by davetsay** [comment] 2023-08-17 22:41
Closing as not reproducible anymore.

**Closed** 2023-09-01 23:17 UTC
Labels: defect
